### ISSUE TITLE
Unexpected Ouput When Reading Array

### ISSUE THREAD

**Issue by FluxIX** [daggaz/json-stream#14]
When visiting with array input at the root scope generates invalid output in the form of a series of child key-value pairs, which is inconsistent with `json.loads`.

For example,
```python
import json_stream
from io import StringIO

def visitation( item, path ):
    print( f"{ path } -> { item }" )

json_stream.visit( StringIO( "[4,3,2]" ), visitation )
```

yields the output:
```
(0,) -> 4
(1,) -> 3
(2,) -> 2
```

**Comment by daggaz** [comment]
Hi,

That's the expected behaviour.

When you use the visitor, the path argument shows what keys you would need to use from the top level item to the one that you are currently visiting.

Hope that makes sense!
