### ISSUE TITLE
How to write data generated by code to JSON using json-stream?

### ISSUE THREAD

**Issue by beck3905** [daggaz/json-stream#15]
Based on the documentation, it is possible to write date back to json that was previously streamed from json using `json_stream.load` and `JSONStreamEncoder`.  However, what if I am building a large dictionary in code and want to stream that to a json file.  Is that possible?

**Comment by daggaz** [comment]
Apologies, I totally missed this issue. If you're still having issue, lemme know, otherwise I'll just close.

**Comment by daggaz** [comment]
Inspired by this issue and my own needs, I've now implemented this in version 1.5.1!

Docs here:
https://github.com/daggaz/json-stream#writing
