### ISSUE TITLE
Utility function for converting persistent data into regular Python equivalents

### ISSUE THREAD

**Issue by smheidrich** [daggaz/json-stream#16]
It would be useful if the library came with some utility function/method to recursively turn `PersistentStreamingJSONList`s and `PersistentStreamingJSONObject`s into regular Python lists and dicts. It's 5 lines of code so people can of course write it themselves but I'd say the operation is common enough in everyday usage that it would make sense to include it.

**Comment by smheidrich** [comment]
For anyone who needs this urgently: I created a separate package containing my draft from #17: https://github.com/smheidrich/json-stream-to-standard-types

**Comment by daggaz** [comment]
I'm not really sure what to do about this one. `to_standard_types()` works, but for some reason I don't like it as a solution. 

I'm tempted to refactor everything to have `dict`/`list` as the base class, and just override _everything_. Though that's probably mad, and I don't know if it solves the actual issue.

Maybe I just don't get the usecases?

**Comment by smheidrich** [comment]
I don't like the implementation either to be honest - it's much simpler to implement with recursion, but then you're needlessly limited by Python's recursion depth limit. No idea if there is a cleaner way to implement it without recursion than how I did it. 

The use cases are just a) that the `json-stream` dict/list equivalents don't implement all `dict` and `list` methods, but you'll often want to use those on dicts/lists you obtained by streaming and b) some other libraries that handle JSON-like data insist on it being composed of regular Python dicts/lists. So any time you e.g. only stream over an outer dict/list to find a specific element, which you then need as a regular dict/list to do further processing, something like `to_standard_types` comes in handy.

I guess your subclass solution would also work for these use cases. At least I can't think of a reason why it wouldn't. Sounds like a lot of work though :P
