### ISSUE TITLE
Allow passing in custom tokenizer?

### ISSUE THREAD

**Issue by smheidrich** [daggaz/json-stream#18]
To make this library a bit faster, I ported the tokenizer to Rust: https://github.com/smheidrich/py-json-stream-rs-tokenizer

Currently this works by monkeypatching the Rust tokenizer over `json-stream`'s own tokenizer in `loader` and `visitor`, which is pretty hacky.

Do you think it would make sense to give `load` and `visit` an extra parameter that allows users to pass in a custom tokenizer? Then I could use that instead of monkeypatching.

**Comment by daggaz** [comment]
Hey, I'd love to see a PR with this?

**Comment by daggaz** [comment]
I've released a new version 1.4.0 with this to pypi, and added to the docs:
https://github.com/daggaz/json-stream#custom-tokenizer

**Comment by smheidrich** [comment]
Perfect, thanks a lot! :+1: I've updated my package as well.
