### ISSUE TITLE
Reconstruct original nested json

### ISSUE THREAD

**Issue by AshleyOboe** [daggaz/json-stream#21]
Hi - I'm having trouble reconstructing the json string after streaming.  My json is multinested and includes arrays and dicts.  I need it to be reconstructed without persisting data so json.dumps isn't an option.  I tried the visitor function but am maybe having difficulty understanding how to recreate original nesting correctly.  Thank you for your help!

**Comment by AshleyOboe** [comment]
Yes, here is an example of a file:
https://github.com/CMSgov/price-transparency-guide/blob/master/examples/in-network-rates/in-network-rates-fee-for-service-single-plan-sample.json

I'm reading it in with json_stream.open(), selecting the "in-network" node, and then am performing functions on each full nested dict in the in-network array.  I do not want to persist the child objects of in-network because that eats up memory and runs really slowly.  When I use the old "to_standard_types" functions it generally works but there's a bug that I'm tracking down that makes me think it may not be recreating perfectly.

**Comment by daggaz** [comment]
where is `to_standard_types()` from?

**Comment by smheidrich** [comment]
Probably from my PR: https://github.com/daggaz/json-stream/pull/17
No idea what is meant by old version though :shrug: I only wrote the one as far as I remember.

**Comment by daggaz** [comment]
I'm looking through old issues, and re-reading this I'm pretty sure you only needed to use the `persistent()` method.

Based on your example, the general structure of your data is:
```jsonp
{
  "in_network": [
     {"some": "data"},
     {"some": "data"},
     ...many objects
  ]
}
```

You can parse this in a memory efficient way thusly:
```python
data = json_stream.load(...)
in_network = data['in_network']  # this will be a transient list
for obj in in_network.persistent():  # iterate the list, but make each output object individually persistent
    # treat obj as a normal dict
    # you can perform any operation even if it's out of stream order
    # at the end each loop iteration, the old obj will be freed from memory
```

You will only use the memory required to store one individual object at a time.
