### ISSUE TITLE
Source distribution for 1.4.0 appears to be missing some 1.4.0 changes

### ISSUE THREAD

**Issue by bjgill** [daggaz/json-stream#22]
Looking at https://files.pythonhosted.org/packages/22/53/77a66646303c51f96be11272c543e40f3cbdafd7685d967626dee2dad7f8/json-stream-1.4.0.tar.gz (linked from https://pypi.org/project/json-stream/#files), it seems to be missing the changes from https://github.com/daggaz/json-stream/commit/f5e68345ac33b398d56f2e5f52174208ca55cc6e (i.e. there's no `tokenizer` parameter). Is this expected? I haven't checked whether the wheel is also affected.

**Comment by daggaz** [comment]
Well that's weird...

I've yanked that release on pypi and published a new 1.4.1 release that actually contains the correct code...

**Comment by bjgill** [comment]
Excellent - thanks. I can now see (and use!) the `tokeniser` parameter.
