### ISSUE TITLE
json-stream is unable to parse JSON consisting of only a primitive value

### ISSUE THREAD

**Issue by jorektheglitch** [daggaz/json-stream#37]
Actual JSON format fully accepts just primitive objects.

> JSON can represent four primitive types (strings, numbers, booleans, and null) and two structured types (objects and arrays).
> — [RFC 8259: The JavaScript Object Notation (JSON) Data Interchange Format](https://datatracker.ietf.org/doc/html/rfc8259) 

So I expect that primitive JSON can be parsed succesfully, but got ValueError while trying to parse them.

Example:
```python
from io import BytesIO
import json_stream

primitives = [
    b"true",
    b"123",
    b"12.3",
    b"'string'",
    b"null",
]
for primitive in primitives:
    f = BytesIO(primitive)
    try:
        json_stream.load(f)
    except Exception as e:
        print(f"Can't parse {primitive!r} due to {type(e).__name__}: {e}")
```
Gives following output:
```
Can't parse b'true' due to ValueError: Unknown operator True
Can't parse b'123' due to ValueError: Unknown operator 123
Can't parse b'12.3' due to ValueError: Unknown operator 12.3
Can't parse b"'string'" due to ValueError: Invalid JSON character: '\'' at index 0
Can't parse b'null' due to ValueError: Unknown operator None
```

**Comment by daggaz** [comment]
@smheidrich look good to you?

**Comment by smheidrich** [comment]
@daggaz Yep looks good :+1:

**Comment by jorektheglitch** [comment]
@daggaz looks good, thank you +1

**Comment by daggaz** [comment]
@jorektheglitch version 2.3.0 just released!

Thanks again for pointing out this issue.
