### ISSUE TITLE
Cannot serialize PersistentStreamingJSONObject/PersistentStreamingJSONList

### ISSUE THREAD

**Issue by frafra** [daggaz/json-stream#6]
Hi,
I can access to the elements when using `.persistent()`, but I cannot treat them as regular Python lists and dictionaries entirely; for example, I cannot serialize them with `json.dumps(...)`. I fixed that by adding `dict` as an inherited class of `PersistentStreamingJSONObject` and `list` for `PersistentStreamingJSONList`.

**Comment by daggaz** [comment]
I've implemented a few helpers for using the built-in json library to dump json-stream data.

See the updated [Readme](https://github.com/daggaz/json-stream/blob/b241946ee8a8f37375d77d347492cb4daa5beb15/README.md#encoding-json-stream-objects) and PR #12.

**Comment by daggaz** [comment]
I'd appreciate any feedback you guys have on the above changes!
